"""microsandbox — Python SDK for secure, fast microVM-based sandboxing."""

import os as _os

from microsandbox._microsandbox import (
    ExecHandle,
    ExecOutput,
    ExecSink,
    FsEntry,
    FsMetadata,
    FsReadStream,
    FsWriteSink,
    Image,
    ImageConfigDetail,
    ImageDetail,
    ImageHandle,
    ImageLayerDetail,
    ImagePruneReport,
    LogEntry,
    LogStream,
    MetricsStream,
    PullSession,
    Sandbox,
    SandboxFsOps,
    SandboxHandle,
    SandboxMetrics,
    SandboxPage,
    SandboxPingResult,
    SandboxSshOps,
    SandboxStopResult,
    SandboxTouchResult,
    SftpClient,
    Snapshot,
    SnapshotHandle,
    SshClient,
    SshOutput,
    SshServer,
    Volume,
    VolumeHandle,
    all_sandbox_metrics,
    backend_scope,
    default_backend_kind,
    install,
    is_installed,
    set_default_backend,
    version,
)
from microsandbox._microsandbox import (
    set_runtime_libkrunfw_path as set_libkrunfw_path,
)
from microsandbox._microsandbox import (
    set_runtime_msb_path as _set_runtime_msb_path,
)
from microsandbox._runtime import msb_path as _msb_path
from microsandbox.agent import (
    FLAG_SESSION_START,
    FLAG_SHUTDOWN,
    FLAG_TERMINAL,
    AgentClient,
    AgentStream,
)
from microsandbox.errors import (
    CloudHttpError,
    ExecFailedError,
    ExecTimeoutError,
    FilesystemError,
    ImageInUseError,
    ImageNotFoundError,
    ImagePullFailedError,
    InvalidConfigError,
    IoError,
    MetricsDisabledError,
    MetricsUnavailableError,
    MicrosandboxError,
    NetworkPolicyError,
    PathNotFoundError,
    SandboxAlreadyExistsError,
    SandboxNotFoundError,
    SandboxNotRunningError,
    SandboxStillRunningError,
    SecretViolationError,
    SnapshotMigrationError,
    TlsError,
    UnsupportedError,
    UnsupportedOperationError,
    VolumeNotFoundError,
)
from microsandbox.events import (
    ExecEvent,
    ExitedEvent,
    LayerDownloadComplete,
    LayerDownloadProgress,
    LayerExtractComplete,
    LayerExtractProgress,
    LayerExtractStarted,
    LayerIndexComplete,
    LayerIndexStarted,
    PullComplete,
    PullProgress,
    Resolved,
    Resolving,
    StartedEvent,
    StderrEvent,
    StdoutEvent,
)
from microsandbox.types import (
    Action,
    DestGroup,
    Destination,
    Direction,
    DiskImageFormat,
    ExitStatus,
    FsEntryKind,
    GiB,
    HostPermissions,
    ImageSource,
    InitConfig,
    LogLevel,
    LogReadSource,
    LogSource,
    MiB,
    MountConfig,
    MountKind,
    Network,
    NetworkDestination,
    NetworkPolicy,
    NetworkProfile,
    Patch,
    PatchConfig,
    PortBinding,
    PortProtocol,
    Protocol,
    PullPolicy,
    RegistryAuth,
    Rlimit,
    RlimitResource,
    RootDisk,
    RootDiskConfig,
    Rule,
    SandboxStatus,
    ScopedUpstreamCACert,
    ScopedVerifyUpstream,
    Secret,
    SecretEntry,
    SecretInjection,
    SecurityProfile,
    Size,
    StatVirtualization,
    Stdin,
    TlsConfig,
    ViolationAction,
    ViolationPolicy,
)

# Pass the bundled msb path to Rust explicitly. `MSB_PATH` remains a user
# override and is still honored first by the native resolver.
if "MSB_PATH" not in _os.environ:
    _bundled_msb = _msb_path()
    if _bundled_msb.exists():
        _set_runtime_msb_path(str(_bundled_msb))

__all__ = [
    # Sandbox lifecycle (native)
    "Sandbox",
    "SandboxHandle",
    "SandboxPage",
    "SandboxStopResult",
    "SandboxPingResult",
    "SandboxTouchResult",
    "PullSession",
    "SandboxStatus",
    "SandboxSshOps",
    "SftpClient",
    "SshClient",
    "SshOutput",
    "SshServer",
    # Low-level agent client
    "AgentClient",
    "AgentStream",
    "FLAG_TERMINAL",
    "FLAG_SESSION_START",
    "FLAG_SHUTDOWN",
    # Execution (native)
    "ExecHandle",
    "ExecOutput",
    "ExecSink",
    "LogEntry",
    "LogStream",
    "MetricsStream",
    "ExitStatus",
    "Stdin",
    "Rlimit",
    "RlimitResource",
    # Events (sealed unions)
    "ExecEvent",
    "StartedEvent",
    "StdoutEvent",
    "StderrEvent",
    "ExitedEvent",
    # Pull progress events
    "PullProgress",
    "Resolving",
    "Resolved",
    "LayerDownloadProgress",
    "LayerDownloadComplete",
    "LayerExtractStarted",
    "LayerExtractProgress",
    "LayerExtractComplete",
    "LayerIndexStarted",
    "LayerIndexComplete",
    "PullComplete",
    # Filesystem (native)
    "SandboxFsOps",
    "FsReadStream",
    "FsWriteSink",
    "FsEntry",
    "FsMetadata",
    # Filesystem (Python enums)
    "FsEntryKind",
    # Volumes
    "Volume",
    "VolumeHandle",
    "MountConfig",
    "MountKind",
    "StatVirtualization",
    "HostPermissions",
    # Snapshots
    "Snapshot",
    "SnapshotHandle",
    # Network
    "Network",
    "NetworkPolicy",
    "NetworkProfile",
    "Rule",
    "Destination",
    "NetworkDestination",
    "Action",
    "Direction",
    "Protocol",
    "PortBinding",
    "PortProtocol",
    "DestGroup",
    # Secrets & TLS
    "Secret",
    "SecretEntry",
    "SecretInjection",
    "ScopedUpstreamCACert",
    "ScopedVerifyUpstream",
    "TlsConfig",
    "ViolationAction",
    "ViolationPolicy",
    # Images / rootfs
    "Image",
    "ImageHandle",
    "ImageDetail",
    "ImageConfigDetail",
    "ImageLayerDetail",
    "ImagePruneReport",
    "ImageSource",
    "RootDisk",
    "RootDiskConfig",
    "DiskImageFormat",
    "PullPolicy",
    "RegistryAuth",
    "LogLevel",
    "SecurityProfile",
    "LogSource",
    "LogReadSource",
    # Patches
    "Patch",
    "PatchConfig",
    # Init handoff
    "InitConfig",
    # Metrics
    "SandboxMetrics",
    "all_sandbox_metrics",
    # Size helpers
    "Size",
    "MiB",
    "GiB",
    # Errors
    "MicrosandboxError",
    "InvalidConfigError",
    "CloudHttpError",
    "SandboxNotFoundError",
    "SandboxNotRunningError",
    "SandboxAlreadyExistsError",
    "SandboxStillRunningError",
    "ExecTimeoutError",
    "ExecFailedError",
    "FilesystemError",
    "PathNotFoundError",
    "VolumeNotFoundError",
    "ImageInUseError",
    "ImageNotFoundError",
    "ImagePullFailedError",
    "NetworkPolicyError",
    "SecretViolationError",
    "SnapshotMigrationError",
    "TlsError",
    "IoError",
    "MetricsDisabledError",
    "MetricsUnavailableError",
    "UnsupportedOperationError",
    "UnsupportedError",
    # Setup
    "install",
    "is_installed",
    "set_libkrunfw_path",
    "set_default_backend",
    "backend_scope",
    "default_backend_kind",
    "version",
]
