// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./microsandbox.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-android-arm64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./microsandbox.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-android-arm-eabi')
        const bindingPackageVersion = require('@superradcompany/microsandbox-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./microsandbox.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-win32-x64-gnu')
        const bindingPackageVersion = require('@superradcompany/microsandbox-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./microsandbox.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-win32-x64-msvc')
        const bindingPackageVersion = require('@superradcompany/microsandbox-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./microsandbox.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-win32-ia32-msvc')
        const bindingPackageVersion = require('@superradcompany/microsandbox-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./microsandbox.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-win32-arm64-msvc')
        const bindingPackageVersion = require('@superradcompany/microsandbox-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./microsandbox.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@superradcompany/microsandbox-darwin-universal')
      const bindingPackageVersion = require('@superradcompany/microsandbox-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./microsandbox.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-darwin-x64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./microsandbox.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-darwin-arm64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./microsandbox.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-freebsd-x64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./microsandbox.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-freebsd-arm64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./microsandbox.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-x64-musl')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./microsandbox.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-x64-gnu')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./microsandbox.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-arm64-musl')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./microsandbox.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-arm64-gnu')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./microsandbox.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-arm-musleabihf')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./microsandbox.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./microsandbox.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-loong64-musl')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./microsandbox.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-loong64-gnu')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./microsandbox.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-riscv64-musl')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./microsandbox.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@superradcompany/microsandbox-linux-riscv64-gnu')
          const bindingPackageVersion = require('@superradcompany/microsandbox-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./microsandbox.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-linux-ppc64-gnu')
        const bindingPackageVersion = require('@superradcompany/microsandbox-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./microsandbox.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-linux-s390x-gnu')
        const bindingPackageVersion = require('@superradcompany/microsandbox-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./microsandbox.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-openharmony-arm64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./microsandbox.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-openharmony-x64')
        const bindingPackageVersion = require('@superradcompany/microsandbox-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./microsandbox.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@superradcompany/microsandbox-openharmony-arm')
        const bindingPackageVersion = require('@superradcompany/microsandbox-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.6.8' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.6.8 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./microsandbox.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@superradcompany/microsandbox-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AgentClient = nativeBinding.AgentClient
module.exports.AttachOptionsBuilder = nativeBinding.AttachOptionsBuilder
module.exports.JsAttachOptionsBuilder = nativeBinding.JsAttachOptionsBuilder
module.exports.DnsBuilder = nativeBinding.DnsBuilder
module.exports.JsDnsBuilder = nativeBinding.JsDnsBuilder
module.exports.ExecHandle = nativeBinding.ExecHandle
module.exports.JsExecHandle = nativeBinding.JsExecHandle
module.exports.ExecOptionsBuilder = nativeBinding.ExecOptionsBuilder
module.exports.JsExecOptionsBuilder = nativeBinding.JsExecOptionsBuilder
module.exports.ExecOutput = nativeBinding.ExecOutput
module.exports.ExecSink = nativeBinding.ExecSink
module.exports.JsExecSink = nativeBinding.JsExecSink
module.exports.FsReadStream = nativeBinding.FsReadStream
module.exports.JsFsReadStream = nativeBinding.JsFsReadStream
module.exports.FsWriteSink = nativeBinding.FsWriteSink
module.exports.JsFsWriteSink = nativeBinding.JsFsWriteSink
module.exports.ImageBuilder = nativeBinding.ImageBuilder
module.exports.JsImageBuilder = nativeBinding.JsImageBuilder
module.exports.ImageHandle = nativeBinding.ImageHandle
module.exports.JsImageHandle = nativeBinding.JsImageHandle
module.exports.InitOptionsBuilder = nativeBinding.InitOptionsBuilder
module.exports.JsInitOptionsBuilder = nativeBinding.JsInitOptionsBuilder
module.exports.InterfaceOverridesBuilder = nativeBinding.InterfaceOverridesBuilder
module.exports.JsInterfaceOverridesBuilder = nativeBinding.JsInterfaceOverridesBuilder
module.exports.LogStream = nativeBinding.LogStream
module.exports.JsLogStream = nativeBinding.JsLogStream
module.exports.MetricsStream = nativeBinding.MetricsStream
module.exports.JsMetricsStream = nativeBinding.JsMetricsStream
module.exports.MountBuilder = nativeBinding.MountBuilder
module.exports.JsMountBuilder = nativeBinding.JsMountBuilder
module.exports.NetworkBuilder = nativeBinding.NetworkBuilder
module.exports.JsNetworkBuilder = nativeBinding.JsNetworkBuilder
module.exports.NetworkPolicyBuilder = nativeBinding.NetworkPolicyBuilder
module.exports.JsNetworkPolicyBuilder = nativeBinding.JsNetworkPolicyBuilder
module.exports.PatchBuilder = nativeBinding.PatchBuilder
module.exports.JsPatchBuilder = nativeBinding.JsPatchBuilder
module.exports.PullProgressCreate = nativeBinding.PullProgressCreate
module.exports.JsPullProgressCreate = nativeBinding.JsPullProgressCreate
module.exports.PullProgressStream = nativeBinding.PullProgressStream
module.exports.JsPullProgressStream = nativeBinding.JsPullProgressStream
module.exports.RegistryConfigBuilder = nativeBinding.RegistryConfigBuilder
module.exports.JsRegistryConfigBuilder = nativeBinding.JsRegistryConfigBuilder
module.exports.RootDiskBuilder = nativeBinding.RootDiskBuilder
module.exports.JsRootDiskBuilder = nativeBinding.JsRootDiskBuilder
module.exports.RuleBuilder = nativeBinding.RuleBuilder
module.exports.JsRuleBuilder = nativeBinding.JsRuleBuilder
module.exports.RuleDestinationBuilder = nativeBinding.RuleDestinationBuilder
module.exports.JsRuleDestinationBuilder = nativeBinding.JsRuleDestinationBuilder
module.exports.Sandbox = nativeBinding.Sandbox
module.exports.SandboxBuilder = nativeBinding.SandboxBuilder
module.exports.JsSandboxBuilder = nativeBinding.JsSandboxBuilder
module.exports.SandboxFsOps = nativeBinding.SandboxFsOps
module.exports.JsSandboxFsOps = nativeBinding.JsSandboxFsOps
module.exports.SandboxHandle = nativeBinding.SandboxHandle
module.exports.JsSandboxHandle = nativeBinding.JsSandboxHandle
module.exports.SecretBuilder = nativeBinding.SecretBuilder
module.exports.JsSecretBuilder = nativeBinding.JsSecretBuilder
module.exports.Setup = nativeBinding.Setup
module.exports.JsSetup = nativeBinding.JsSetup
module.exports.SftpClient = nativeBinding.SftpClient
module.exports.JsSftpClient = nativeBinding.JsSftpClient
module.exports.Snapshot = nativeBinding.Snapshot
module.exports.JsSnapshot = nativeBinding.JsSnapshot
module.exports.SnapshotBuilder = nativeBinding.SnapshotBuilder
module.exports.JsSnapshotBuilder = nativeBinding.JsSnapshotBuilder
module.exports.SnapshotHandle = nativeBinding.SnapshotHandle
module.exports.JsSnapshotHandle = nativeBinding.JsSnapshotHandle
module.exports.SshClient = nativeBinding.SshClient
module.exports.JsSshClient = nativeBinding.JsSshClient
module.exports.SshServer = nativeBinding.SshServer
module.exports.JsSshServer = nativeBinding.JsSshServer
module.exports.TlsBuilder = nativeBinding.TlsBuilder
module.exports.JsTlsBuilder = nativeBinding.JsTlsBuilder
module.exports.ViolationActionBuilder = nativeBinding.ViolationActionBuilder
module.exports.JsViolationActionBuilder = nativeBinding.JsViolationActionBuilder
module.exports.Volume = nativeBinding.Volume
module.exports.JsVolume = nativeBinding.JsVolume
module.exports.VolumeBuilder = nativeBinding.VolumeBuilder
module.exports.JsVolumeBuilder = nativeBinding.JsVolumeBuilder
module.exports.VolumeFs = nativeBinding.VolumeFs
module.exports.JsVolumeFs = nativeBinding.JsVolumeFs
module.exports.VolumeFsReadStream = nativeBinding.VolumeFsReadStream
module.exports.JsVolumeFsReadStream = nativeBinding.JsVolumeFsReadStream
module.exports.VolumeFsWriteSink = nativeBinding.VolumeFsWriteSink
module.exports.JsVolumeFsWriteSink = nativeBinding.JsVolumeFsWriteSink
module.exports.VolumeHandle = nativeBinding.VolumeHandle
module.exports.JsVolumeHandle = nativeBinding.JsVolumeHandle
module.exports.allSandboxMetrics = nativeBinding.allSandboxMetrics
module.exports.defaultBackendKind = nativeBinding.defaultBackendKind
module.exports.imageGet = nativeBinding.imageGet
module.exports.imageInspect = nativeBinding.imageInspect
module.exports.imageList = nativeBinding.imageList
module.exports.imageLoad = nativeBinding.imageLoad
module.exports.imagePrune = nativeBinding.imagePrune
module.exports.imageRemove = nativeBinding.imageRemove
module.exports.imageSave = nativeBinding.imageSave
module.exports.install = nativeBinding.install
module.exports.isInstalled = nativeBinding.isInstalled
module.exports.popDefaultBackend = nativeBinding.popDefaultBackend
module.exports.pushDefaultBackend = nativeBinding.pushDefaultBackend
module.exports.setDefaultBackend = nativeBinding.setDefaultBackend
module.exports.setRuntimeLibkrunfwPath = nativeBinding.setRuntimeLibkrunfwPath
module.exports.setRuntimeMsbPath = nativeBinding.setRuntimeMsbPath
